version: '3.9'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: taskmanager-app
    ports:
      - "2030:2030"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskdb
      SPRING_DATASOURCE_USERNAME: taskuser
      SPRING_DATASOURCE_PASSWORD: taskpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:15
    container_name: taskmanager-db
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: taskmanager-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  db_data: